### ISSUE TITLE
Additional ECC curves

### ISSUE THREAD

**Issue by rahiparikh** [bitwiseshiftleft/sjcl#347] opened 2017-11-13 20:14 UTC
Let me start by saying that you guys have designed an awesome library. I was going through various functions/features and noticed the list of curves that you support for ECC. I came across https://safecurves.cr.yp.to/ that lists a few of the implemented curves as non-preferred choices. 

I was wondering if it would be possible to support some of the recommended curves.

**Comment by emdiet** [comment] 2017-11-19 01:29
I think with new new `new sjcl.ecc.curve()` you can define whatever you want (I haven't gotten it to work though and something was broken when I tried this)

**Comment by Nilos** [comment] 2017-11-19 15:28
Duplicate of #158 
Also see the discussion there why this is harder than it might seem.

**Closed by Nilos** 2017-11-19 15:28 UTC
